In [25]:
# Import librararies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [26]:
# load the dataset

data = pd.read_csv('car_data.csv')
data.head()

name  year  selling_price  km_driven  mileage  \
0        Maruti Swift Dzire VDI  2014         450000     145500    23.40   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000    21.14   
2      Honda City 2017-2020 EXi  2006         158000     140000    17.70   
3     Hyundai i20 Sportz Diesel  2010         225000     127000    23.00   
4        Maruti Swift VXI BSIII  2007         130000     120000    16.10   

   engine  max_power  
0  1248.0      74.00  
1  1498.0     103.52  
2  1497.0      78.00  
3  1396.0      90.00  
4  1298.0      88.20

In [27]:
# select the needed data point
# independent and dependent variable
x = data.iloc[:, 3].values.reshape(-1, 1)
y = data.iloc[:, 2].values.reshape(-1, 1)

In [28]:
x

array([[145500],
       [120000],
       [140000],
       ...,
       [120000],
       [ 25000],
       [ 25000]], shape=(7906, 1))

In [29]:
y


array([[450000],
       [370000],
       [158000],
       ...,
       [382000],
       [290000],
       [290000]], shape=(7906, 1))

In [30]:
# linear regression
lin_reg = LinearRegression()
lin_reg.fit(x, y)


LinearRegression()

In [32]:
# make prediction based on the trained model
y_pred = lin_reg.predict(x)
y_pred

array([[406949.09153643],
       [488104.10764868],
       [424453.11461946],
       ...,
       [488104.10764868],
       [790446.32453745],
       [790446.32453745]], shape=(7906, 1))

In [34]:
# create a dataframe to see the actual and the predicted
data_pred = pd.DataFrame({'Actual': y.flatten(), 'Predicted': y_pred.flatten()})
data_pred

Actual      Predicted
0     450000  406949.091536
1     370000  488104.107649
2     158000  424453.114619
3     225000  465826.260088
4     130000  488104.107649
...      ...            ...
7901  320000  519929.604163
7902  135000  491286.657300
7903  382000  488104.107649
7904  290000  790446.324537
7905  290000  790446.324537

[7906 rows x 2 columns]